# Generated by Django 5.0.6 on 2024-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haven', '0002_diary_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='Private', max_length=10),
        ),
    ]
